using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.Serialization;
namespace Ticketing.Infrastructure.Messaging
{
    /// <summary>
    /// Base request class for Messaging pattern.
    /// </summary>
    /// 
    [DataContract(IsReference=true)]
    public abstract class RequestBase: IRequest
    {
        /// <summary>
        /// Unique identifier of the request generated by the client for each unique request. 
        /// Can be used to check status of long running operations and/or any asynchronous call.
        /// </summary>
        [DataMember]
        public Guid RequestToken { get; set; }
    }
}
